### ISSUE TITLE
Only preloading one font

### ISSUE THREAD

**Issue by deadcoder0904** [tailwindlabs/blog.tailwindcss.com#10]
I noticed on https://github.com/tailwindcss/blog/blob/master/src/pages/_document.js#L39-L45 you are preloading only `Inter-roman.var-latin.woff2?3.13` while you also have `Inter-italic.var-latin.woff2?3.13`.

My question is why aren't you preloading the `italic` one?

Also, there are 2 unused fonts in `public/fonts` folder.

**Comment by bradlc** [comment]
Hey @deadcoder0904. This is deliberate since the regular version of the font is much more important than the italic version, which is rarely used. I think that the italic font is lower priority than everything else so the preload isn't desirable.

Regarding the unused fonts, I think we'll leave those there for now as they are the original versions that the `*-latin` subsets were created from. They may be useful if we want to update or create new subsets. Thank you for the heads-up though!

**Comment by deadcoder0904** [comment]
Cool thanks for the answer. @bradlc love your work, Tailwind Intellisense is rad, so is Tailwind Play & the new landing page :)
